Repository neuralmagic/sparsify, pull requests merged in 2023-07, with the labels that each got.

#250 Display right deployment directory location
  src/sparsify/auto/tasks/runner.py
Labels: bug

#233 Add environment checks
  setup.py
  src/sparsify/check_environment/__init__.py
  src/sparsify/check_environment/gpu_device.py
  src/sparsify/check_environment/main.py
  src/sparsify/check_environment/ort_health.py
  src/sparsify/check_environment/pathway_checks.py
  src/sparsify/cli/run.py
Labels: mle-team

#252 Turn QAT folding on by default
  src/sparsify/auto/tasks/image_classification/args.py
  src/sparsify/auto/tasks/transformers/args.py
Labels: mle-team

#256 Fix Sparsifyml not installed prompt
  src/sparsify/check_environment/ort_health.py
Labels: enhancement

#275 Update link in deployment_instructions.md
  src/sparsify/auto/tasks/deployment_instructions.md
Labels: mle-team
