Repository neuralmagic/sparsify, pull requests merged in 2023-06, with the labels that each got.

#214 Update integration and unit tests
  src/sparsify/auto/tasks/args.py
  src/sparsify/auto/tasks/image_classification/args.py
  src/sparsify/auto/tasks/runner.py
  src/sparsify/auto/tasks/transformers/args.py
  tests/integration/auto/test_cli_run.py
  tests/sparsify/utils/test_task_name.py
Labels: mle-team

#216 Add login step to test setup
  .github/workflows/test-check.yaml
Labels: mle-team

#223 [BugFixes] Fix failing tests in `sparsify.alpha`
  tests/sparsify/auto/test_main.py
Labels: bug, mle-team

#224 [Cherry-pick] Relevant Sparsify.alpha updates to Sparsify.beta
  .github/workflows/test-check.yaml
  .gitignore
  setup.py
  src/sparsify/auto/scripts/main.py
  src/sparsify/auto/tasks/args.py
  src/sparsify/auto/tasks/image_classification/args.py
  src/sparsify/auto/tasks/image_classification/runner.py
  src/sparsify/auto/tasks/object_detection/yolov5/args.py
  src/sparsify/auto/tasks/object_detection/yolov5/runner.py
  src/sparsify/auto/tasks/runner.py
  src/sparsify/auto/tasks/transformers/args.py
  src/sparsify/auto/tasks/transformers/runner.py
  src/sparsify/auto/utils/helpers.py
  src/sparsify/cli/opts.py
  src/sparsify/cli/run.py
  src/sparsify/login.py
  src/sparsify/schemas/auto_api.py
  src/sparsify/version.py
  tests/integration/auto/test_cli_run.py
  tests/sparsify/utils/test_task_name.py
Labels: mle-team

#222 Deprecate Py37
  .github/ISSUE_TEMPLATE/bug_report.md
  DEVELOPING.md
  README.md
  setup.py
Labels: mle-team

#221 Add Pydantic Models for Sparsify CLIs
  src/sparsify/cli/utils/__init__.py
  src/sparsify/cli/utils/args.py
Labels: mle-team

#227 Default num_samples to None
  src/sparsify/cli/run.py
Labels: mle-team

#231 Remove dev print statements from IC runner
  src/sparsify/auto/tasks/image_classification/runner.py
Labels: mle-team

#232 Fix incomplete wheel build
  src/sparsify/auto/scripts/__init__.py
Labels: mle-team

#228 Update GHA file for auto tests
  .github/workflows/test-check.yaml
Labels: bug, mle-team

#235 Add support to download non-nightly sparsifyml package
  src/sparsify/login.py
Labels: bug

#236 [Beta] Add support to download non-nightly sparsifyml package
  src/sparsify/login.py
Labels: bug
